name: Tests

on:
  workflow_call:
    inputs:
      solana_cli_version:
        required: true
        type: string
      node_version:
        required: true
        type: string
      anchor_version:
        required: true
        type: string
      python_version:
        required: true
        type: string
      solana_rpc:
        required: true
        type: string
env:
  SOLANA_CLI_VERSION: ${{ inputs.solana_cli_version }}
  NODE_VERSION: ${{ inputs.node_version }}
  ANCHOR_VERSION: ${{ inputs.anchor_version }}
  SOLANA_RPC: ${{ inputs.solana_rpc }}
  PYTHON_VERSION: ${{ inputs.python_version }}
  CARGO_CACHE_PATH: |
    ~/.cargo/bin/
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    ./target/

jobs:
  test-core:
    name: Formatting tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: cargo fmt -- --check
      - run: npm i prettier
      - run: npm run lint 

  test-defios:
    name: Test DefiOS contracts
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
      - uses: ./.github/actions/setup-solana/
      - uses: ./.github/actions/setup-ts/
      - uses: ./.github/actions/setup-amman/
      - uses: ./.github/actions/setup-anchor/
      - run: anchor build --arch sbf 
      - run: anchor deploy
      - run: anchor keys sync
      - run: anchor build --arch sbf
      - run: anchor deploy
      - run: anchor test --arch sbf --skip-local-validator  --skip-deploy --skip-build --run tests/DefiOS
      - uses: ./.github/actions/parse-program-compute/

  test-skill-validator:
    name: Test SkillValidator contracts
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
      - uses: ./.github/actions/setup-solana/
      - uses: ./.github/actions/setup-ts/
      - uses: ./.github/actions/setup-amman/
      - uses: ./.github/actions/setup-anchor/
      - run: anchor build --arch sbf
      - run: anchor deploy
      - run: anchor keys sync
      - run: anchor build --arch sbf
      - run: anchor deploy
      - run: anchor test --arch sbf --skip-local-validator --skip-deploy --skip-build --run tests/SkillValidator
      - uses: ./.github/actions/parse-program-compute/
